[project]
name = "sentinal-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.27",
    "python-docx>=1.1.2",
    "streamlit>=1.45.1",
]
